mlflow:
  tracking_uri: "http://127.0.0.1:5000/"
  experiment_name: "Nada_D2T"

seed: 0
model: "t5-base"
specify_target_with_prefix: True  # specify target either as a prefix to the encoder input, or with the decoder_start_token_id
fast_dev_run: False

# training
mode: "t2g"
epochs: 5
lr: 1.0e-4
lr_scheduler: "linear"  # can also be 'constant'
batch_size_train: 4
max_grad_norm: 1.0
# training (specific to unsupervised)
generate_method: "greedy"  # 'greedy', 'sample', 'top_k'
sample_noise_fun:  # which noise functions to sample from?
  - "swap"
  - "drop"
  - "blank"
  - "rule"
  - "repeat"

loss:
  cycle: "vae" #"vae" or "regular"
  auto: "denoising"  # "vae" or "denoising"

beta_n_cycle: 4  # number of cycles for the beta-VAE schedule (-1 for regular VAE: constant beta=1)

# validation
num_beams_t2g: 8
num_beams_g2t: 5
batch_size_val: 4

# logging
checkpoints: "on_training_end"  # 'no', 'on_training_end', or 'on_epoch_end'
log_every_n_steps: 100  # for training metrics (evaluation is always done after each epoch)